import { ComponentProps } from 'react';
import {
  AlertTriangle,
  AtSign,
  BadgeCheck,
  Bell,
  Building2,
  Calendar,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  Camera,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Circle,
  CircleDollarSign,
  CircleDot,
  Dumbbell,
  Edit,
  Eye,
  EyeOff,
  ExternalLink,
  CreditCard,
  CreditCardIcon,
  Download,
  Grid3X3,
  HeartPulse,
  HelpCircle,
  FileText,
  Globe,
  Home,
  Info,
  Languages,
  LayoutDashboard,
  Link as LinkIcon,
  ListChecks,
  LockKeyhole,
  LogOut,
  MapPin,
  Mail,
  Menu,
  MessageCircleWarning,
  MoreHorizontal,
  Phone,
  Plus,
  RefreshCw,
  RotateCcw,
  Save,
  Search,
  Send,
  Settings,
  Shield,
  ShieldCheck,
  Trophy,
  TrendingUp,
  TrendingDown,
  ArrowUp,
  ArrowDown,
  Activity,
  Zap,
  Wallet,
  Sparkles,
  Trash2,
  User,
  UserCog,
  UserCheck,
  UserCircle,
  UserRoundX,
  UserPlus,
  Users,
  UsersRound,
  WalletCards,
  XCircle,
  X,
} from 'lucide-react';

type IconProps = {
  name?: string;
  size?: number;
  color?: string;
  style?: React.CSSProperties;
  className?: string;
};

const iconMap: Record<string, typeof Circle> = {
  'account-balance-wallet': WalletCards,
  add: Plus,
  'alternate-email': AtSign,
  apartment: Home,
  apps: Grid3X3,
  'arrow-back': ChevronLeft,
  'arrow-forward': ChevronRight,
  'assignment-ind': UserCheck,
  calendar: Calendar,
  'calendar-today': CalendarDays,
  cancel: XCircle,
  check: Check,
  'check-circle': CheckCircle,
  'check-circle-outline': CheckCircle,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  close: X,
  'credit-card-off': CreditCardIcon,
  dashboard: LayoutDashboard,
  'date-range': CalendarDays,
  delete: Trash2,
  edit: Edit,
  'emoji-events': Trophy,
  'error-outline': MessageCircleWarning,
  'event-available': CalendarCheck,
  'event-busy': CalendarClock,
  'expand-less': ChevronDown,
  'expand-more': ChevronDown,
  'fact-check': ListChecks,
  'family-restroom': Users,
  'file-download': Download,
  'fitness-center': Dumbbell,
  'flash-on': CircleDot,
  'grid-view': LayoutDashboard,
  'group-off': UserRoundX,
  groups: UsersRound,
  'help-outline': HelpCircle,
  home: Home,
  'info-outline': Info,
  'insert-chart-outlined': TrendingUp,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  'arrow-upward': ArrowUp,
  'arrow-downward': ArrowDown,
  north: ArrowUp,
  south: ArrowDown,
  'show-chart': Activity,
  'auto-graph': TrendingUp,
  'monitoring': Activity,
  bolt: Zap,
  'account-balance': Wallet,
  'auto-awesome': Sparkles,
  'event': CalendarDays,
  'keyboard-arrow-down': ChevronDown,
  language: Languages,
  leaderboard: Trophy,
  link: LinkIcon,
  'location-on': MapPin,
  lock: LockKeyhole,
  'lock-outline': LockKeyhole,
  logout: LogOut,
  mail: Mail,
  'mark-email-read': Mail,
  'medical-services': HeartPulse,
  menu: Menu,
  'monitor-heart': HeartPulse,
  'more-horiz': MoreHorizontal,
  notifications: Bell,
  'notifications-none': Bell,
  payment: CreditCard,
  payments: WalletCards,
  people: UsersRound,
  'person-add': UserPlus,
  'person-add-alt-1': UserPlus,
  person: User,
  'person-outline': UserCircle,
  phone: Phone,
  'photo-camera': Camera,
  place: MapPin,
  plus: Plus,
  'radio-button-unchecked': Circle,
  receipt: FileText,
  'receipt-long': FileText,
  refresh: RefreshCw,
  'restart-alt': RotateCcw,
  save: Save,
  schedule: CalendarClock,
  search: Search,
  send: Send,
  settings: Settings,
  shield: Building2,
  sports: Trophy,
  'admin-panel-settings': UserCog,
  'sports-basketball': Trophy,
  'basketball-ball': Trophy,
  'credit-card': CreditCard,
  terrain: MapPin,
  timer: CalendarClock,
  verified: BadgeCheck,
  'verified-user': ShieldCheck,
  visibility: Eye,
  'visibility-off': EyeOff,
  warning: AlertTriangle,
  'warning-amber': AlertTriangle,
  badge: BadgeCheck,
};

function Icon({ name = 'circle', size = 20, color = 'currentColor', style, className }: IconProps) {
  const ResolvedIcon = iconMap[name] || Circle;

  return (
    <span
      aria-hidden="true"
      className={className}
      style={{
        alignItems: 'center',
        color,
        display: 'inline-flex',
        fontSize: size,
        height: size,
        justifyContent: 'center',
        lineHeight: 1,
        width: size,
        ...style,
      }}
      title={name}
    >
      <ResolvedIcon size={size} strokeWidth={2.2} />
    </span>
  );
}

const glyphMap = new Proxy({}, { get: () => 1 });

export const MaterialIcons = Object.assign(Icon, { glyphMap });
export const FontAwesome5 = Object.assign(Icon, { glyphMap });
export const FontAwesome = Object.assign(Icon, { glyphMap });
export const Ionicons = Object.assign(Icon, { glyphMap });
export const Feather = Object.assign(Icon, { glyphMap });
export type IconComponent = typeof Icon;
export type IconPropsType = ComponentProps<typeof Icon>;
